マッチング画面作成
miyazaki0505/miya_portfolio pull request #10
Opened 2022-01-04 08:21 UTC by miyazaki0505

お疲れ様です！
マッチング画面の作成が完了いたしました。

ご確認の程よろしくお願いいたします。

2022-01-04 12:30 UTC, quest-academia requested changes
レビューしました

2022-01-04 12:30 UTC, quest-academia commented on resources/views/users/match.blade.php
> +            @if( $user->language == $project->language && $user->work_location == $project->work_location && $user->occupation == $project->occupation)
Auth::userでいける？

2022-01-04 12:30 UTC, quest-academia commented on resources/views/users/match.blade.php
> +        <p>{{ Auth::user()->last_name."さんのご希望の条件と一致する案件はこちらです。" }}</p>
一致ゼロ件の場合

2022-01-04 12:30 UTC, quest-academia commented on app/Http/Controllers/UsersController.php
> +        $projects = Project::orderBy('id', 'desc')->paginate(5);
この時点で検索をかける

2022-01-06 18:20 UTC, miyazaki0505 commented
お疲れ様です！
指摘点の修正が完了いたしました
。

対象のサンプルユーザーをシーダーに作成いたしましたのでご確認時ご利用ください。

マッチする案件が「ある」ユーザー
アドレス：tokuda@sample.com
パスワード：tokuda

マッチする案件が「ない」ユーザー
アドレス：katou@sample.com
パスワード：katou

なおこのタイミンで、ログアウトの戻るボタンの挙動も修正を入れています。

ご確認の程よろしくお願いいたします。

2022-01-07 04:36 UTC, quest-academia approved these changes
動作確認しまして、OKです！
完璧です☺️

コードもかなりすっきりとよくなりましたね！
クエリビルダの使い方もバッチリです！

今後追加機能を実装するなら・・・という話ですが
その場合、ユーザの言語や勤務希望先などのユーザ詳細ページと
ユーザの情報変更ページもあれば、
ユーザ情報を変更すればマッチング内容が変わってくることが分かって
より良いなと思いました！

今回はこれでOKですのでマージお願いします✨

2022-01-07 10:48 UTC, merged