検索機能実装
miyazaki0505/miya_portfolio pull request #11
Opened 2022-01-09 05:45 UTC by miyazaki0505

お疲れ様です！
検索機能の実装が完了しました。

どの組み合わせでの検索にも対応できるようにしています。
合わせてヘッダーも修正しております。

ご確認よろしくお願いいたします。

2022-01-11 02:36 UTC, SekiYukihiro requested changes
全体的に素晴らしいですね！
きれいにコードもかけていると思います！

少しレベルが高い話になりますが
指摘させて頂きましたので、ご確認下さい！

2022-01-11 02:36 UTC, SekiYukihiro commented on app/Http/Controllers/ProjectsController.php
> +        }
こちらはなぜ８０万の場合と、７０万以下の場合で
場合分けしているのでしょう？

2022-01-11 02:36 UTC, SekiYukihiro commented on app/Http/Controllers/ProjectsController.php
> +            });
少しレベルが高い話になりますが、
% や _ を検索欄に入れて検索してみて下さい。
すると、上記のもの（ワイルドカード）では検索できないと思います。

そこで、ワイルドカードを文字列として検索できるようにするために
下記の記事のようにワイルドカードを文字列化するなどの対応が必要になります。

一度やってみて下さい！
https://teratail.com/questions/216459

2022-01-11 02:36 UTC, SekiYukihiro commented on app/Http/Controllers/ProjectsController.php
> +    public function search(Request $request)
一度検索実行してから
検索画面に戻ったときに、
検索キーワードなどが全て消えてしまうので
消さずにキーワードを保持できるように考えてみましょう！

2022-01-11 02:36 UTC, SekiYukihiro commented on app/Http/Controllers/ProjectsController.php
> +    public function search(Request $request)
ページネーションで先のページに進んだ場合も
検索ワードなどが消えてしまう気がします。

2022-01-11 02:36 UTC, SekiYukihiro commented on app/Http/Controllers/ProjectsController.php
> +    public function search(Request $request)
ヒントです。
https://zakkuri.life/laravel%E3%83%9A%E3%83%BC%E3%82%B8%E3%83%8D%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%A7%E6%A4%9C%E7%B4%A2%E3%83%91%E3%83%A9%E3%83%A1%E3%83%BC%E3%82%BF%E3%82%92%E4%BF%9D%E6%8C%81%E3%81%99%E3%82%8B/

2022-01-16 09:45 UTC, miyazaki0505 commented
お疲れ様です。
大変遅くなり申し訳ございません。

今回の修正点は、

①月額報酬80万〜のif文のコード修正
②ワイルドカードを文字列化
③「検索画面へ戻る」ボタン押下後の検索欄の値の保持
④ページネーション２ページ目以降、URLの?後の値の保持

となります。

ご確認よろしくお願いいたします。
URL：http://192.168.33.11

2022-01-17 08:00 UTC, SekiYukihiro requested changes
セッションの利用は素晴らしいですね！
良い感じです😃

ワイルドカードが検索できないなど、動作確認ができていなさそうな部分がありましたので
書きました（いいねが混じっているところも・・・）。

ご確認下さい！

2022-01-17 08:00 UTC, SekiYukihiro commented on app/Http/Controllers/ProjectsController.php
> +        return str_replace(['\\', '%', '_'], ['\\\\', '\%', '\_'], $str);
%や_で検索しても全件表示されるようですが、
動画確認されましたか？

2022-01-17 08:00 UTC, SekiYukihiro commented on app/User.php
> +    }
いいね機能が入っている気がします・・・。
可能であれば除きましょう！

2022-01-17 16:49 UTC, miyazaki0505 commented
お疲れ様です！
ワイルドカードのエスケープが完了いたしました。
事前の動作確認に関して、大文字「％」で確認してしまっていました。失礼いたしました。

いいね機能部分をpushしてしまっていた箇所は消しました。

また、「app/Project.php」「resources/views/projects/project_detail.blade.php」にてコンフリクトが起きておりましたので、一度pushさせていいただいております。

ご確認よろしくお願いいたします。
http://192.168.33.11/

2022-01-19 10:23 UTC, miyazaki0505 commented
お疲れ様です！
複数ワードでの検索機能の実装が完了いたしました。
search_input.blade.phpのフリーワード検索窓にあった空白も削除させていただきました。

ご確認の程よろしくお願いいたします。
http://192.168.33.11/

2022-01-20 10:31 UTC, SekiYukihiro approved these changes
確認しました！

クロージャを用いたAND複数検索ができていて素晴らしいと思います✨
めちゃいいですね。

スペースの問題も解消されており完璧です、この調子で
次に進みましょう☺️

マージしてください！

2022-01-20 11:07 UTC, merged