いいね機能実装
miyazaki0505/miya_portfolio pull request #12
Opened 2022-01-20 11:49 UTC by miyazaki0505

お疲れ様です！
いいね機能を実装完了いたしました。

また、マッチング画面にて、
マッチング案件が0件のユーザーの画面に、

マッチングした時のタイトル（〜さんのご希望の条件と一致する案件はこちらです。）と、
マッチングしていない時のタイトル（〜さんのご希望の条件と一致する案件はございませんでした。）が

両方出てきてしまっていたので、いいねブランチで修正させていただきました。
（対象ファイルは、match.blade.php と  ProjectsController.phpになります。）

ご確認よろしくお願いいたします。

http://192.168.33.11/

2022-01-21 14:33 UTC, SekiYukihiro requested changes
いいね！機能は全体的によくできていると思います！✨
いくつかバグなどある部分もあったので、指摘しておりますので修正してみてください！

また、今回の機能と関係あるかわかりませんが、
ログインした状態で検索画面にいくと強制的にログアウトしてしまうようですので修正しましょう！

2022-01-21 14:33 UTC, SekiYukihiro commented on app/Http/Controllers/LikeController.php
> +            $projects = $users->likes()->orderBy('id', 'asc')->paginate(5);
いいねした順番で並べられていますが、
降順の方が、直前に良いねしたものがわかりやすくいいかもしれませんね

2022-01-21 14:33 UTC, SekiYukihiro commented on resources/views/users/show_like.blade.php
> +            <div class="pagination justify-content-center">{{ $projects->links() }}</div>
ページネーションを押して２ページ目にいこうとすると（下記URL）
http://192.168.33.11/showDetail/2/like?page=2
下記のエラーが出ましたので修正しましょう！
また、ページネーションのテストもしっかり行いましょう。

`The GET method is not supported for this route. Supported methods: POST.`

2022-01-21 14:33 UTC, SekiYukihiro commented on app/Http/Controllers/LikeController.php
> +            $projects = $users->likes()->orderBy('id', 'asc')->paginate(5);
上に同じ

2022-01-21 14:33 UTC, SekiYukihiro commented on app/Http/Controllers/LikeController.php
> +            $projects = $users->likes()->orderBy('id', 'asc')->paginate(5);
上に同じ

2022-01-21 14:33 UTC, SekiYukihiro commented on app/User.php
> +    public function is_liking($projectId)
メソッド名は他のところでは
キャメルケースで使っていたと思うので、キャメルケースで統一しましょう！

2022-01-21 14:33 UTC, SekiYukihiro commented on resources/views/users/show_like.blade.php
> +            <p class="mt-4">気になる案件がございましたらぜひいいねしてみてください！</p>
「現在いいねされた案件はありません。
　気になる案件がございましたらぜひいいねしてみてください！」

の方が、良いねされているのが0件だとわかるのでより良いと思います！

2022-01-23 11:59 UTC, miyazaki0505 commented
お疲れ様です！
遅くなり申し訳ございません。
いいね機能の修正完了いたしました。

検索を押すと強制ログアウトする件に関しまして、sessionのデータ削除はflush()ではなくforget()を使用し解決いたしました。
ページネーションのエラーに関しまして、$projectsの定義が重複していたため起きていたとみられます。
（ここに気づくのに時間がかかりました。）

ご確認の程よろしくお願いいたします。
http://192.168.33.11/

2022-01-27 09:06 UTC, miyazaki0505 commented
お疲れ様です！
今回の修正点は以下です。

①新しくいいねされた案件がいいねページの一番上に表示されるようにする
②ページネーションにて２ページ目に行く時のエラー解消（PRG）
③その他、ご指摘いただいた表記の変更

ご確認よろしくお願いいたします。

http://192.168.33.11/

アドレス：tokuda@sample.com
パスワード：tokuda
＊ご確認時こちらのアカウントをご利用ください。

2022-01-29 10:15 UTC, SekiYukihiro approved these changes
確認しまして、PRGなど含め
修正点完璧だと思います😆

マージお願いいたします！

2022-01-29 21:36 UTC, merged