応募機能作成
miyazaki0505/miya_portfolio pull request #13
Opened 2022-01-31 20:35 UTC by miyazaki0505

お疲れ様です！
応募機能の実装が完了いたしました。

今回作成・修正した箇所は以下です。

①案件詳細画面から応募ボタン押下→
　❶初めて応募する案件の場合　：確認画面として、新規登録時入力したユーザー情報を表示
　❷一度応募している案件の場合：「すでに応募済みです」の文言ページに遷移

②❶に遷移後さらに確認画面内応募ボタンを押下→「応募完了」ページに遷移

③応募が完了した案件はマイページ内の応募履歴ページに表示される

④前回からの修正
　❶show_login.blade.php　ファイル名を他のファイルと統一し、キャメルケースからスネークケースに修正
　❷show_like.blade.php　　タイトルとコメントの行間を他のタブと同じ行間に修正

ご確認の程よろしくお願いいたします。

http://192.168.33.11/

＊ご確認いただく際、こちらのアカウントをご使用ください。
メールアドレス：tokuda@sample.com
パスワード　　：tokuda

2022-02-02 01:56 UTC, SekiYukihiro requested changes
PRGも理解されていて、エラーもなく
全体的にコードもまとまっていて素晴らしい出来だと思います✨
なので細かい命名の件を書きましたのでその点だけ確認下さい！

あと、filechangesには書きませんでしたが、
応募ボタンと戻るボタンの色が同じなので、色を変えた方がわかりやすいと思いました！

2022-02-02 01:56 UTC, SekiYukihiro commented on app/Http/Controllers/ApplicationController.php
> +                $language = $languages[$key];
他の部分でも同じ様な記述があるかもしれませんが
（細かい点ですが）
$language と $languages が１文字しか違わないので
変数の違いが分かりづらく可読性があまりよくないかと思います。
それぞれの違いが分かりやすい名前に変えましょう！

以下の行で同じような箇所があると思うので、以下同文です

2022-02-02 01:56 UTC, SekiYukihiro commented on app/Http/Controllers/ApplicationController.php
> +    public function already($id)
こちらも関数の命名の件ですが、
alreadyだと何か分かりづらいので
モデルと同じくalreadyApplyなどの関数名の方がいいと思います。

2022-02-02 13:18 UTC, miyazaki0505 commented
お疲れ様です！
応募機能の修正が完了いたしました。

今回修正した箇所です。

①already関数の関数名修正
②languages等の変数名の修正（検索機能やいいね機能でもご指摘いただいた書き方をしてしまっておりますが、応募機能以外は修正しておりません。）
③案件詳細画面の戻るボタンのデザイン変更


ご確認の程よろしくお願いいたします。

http://192.168.33.11/

＊ご確認いただく際、こちらのアカウントをご使用ください。
メールアドレス：tokuda@sample.com
パスワード　　：tokuda

2022-02-03 03:34 UTC, SekiYukihiro approved these changes
確認して、OKです☺️
これで実装は一旦終了ですね。
この３ヶ月ほど、お疲れ様でした！✨

2022-02-03 09:58 UTC, merged