Feature/miya/register
miyazaki0505/miya_portfolio pull request #4
Opened 2021-12-14 08:47 UTC by miyazaki0505

お疲れ様です！

新規ユーザー登録機能を実装しました。
遅くなり申し訳ございません。

前回一度行ったプルリクを削除し、新たにプルリクを作成しています。
やり方として間違っておりましたらご指導ください。

ご確認の程よろしくお願いいたします。

2021-12-14 12:34 UTC, quest-academia requested changes
レビューしました。ご確認願います。

2021-12-14 12:34 UTC, quest-academia commented on database/migrations/2014_10_12_000000_create_users_table.php
> -            $table->text('about_myself');
テキストのままでOK

2021-12-14 12:34 UTC, quest-academia commented on config/language.php
> +);
return [
    '0' => '未選択',
    '1' => 'Java', 
    '2' => 'PHP', 
    '3' => 'C/C++', 
    '4' => 'C#',
    '5' => 'Ruby',
    '6' => 'Python',  
    '7' => 'JavaScript', 
    '8' => 'Swift',
    '9' => 'Go',
    '10' => 'Kotlin', 
    '11' => 'HTML5/CSS3'
];

2021-12-14 12:34 UTC, quest-academia commented on config/language.php
> +?>
PHP終了タグ不要

2021-12-14 12:34 UTC, quest-academia commented on resources/views/commons/header.blade.php
> +</header>
空行

2021-12-15 04:29 UTC, quest-academia requested changes
いくつかコメントを書きましたので
修正お願いいたします☺️

2021-12-15 04:29 UTC, quest-academia commented on resources/views/auth/register.blade.php
> +                <div class="text-center"><input type="submit" class="btn btn-secondary mt-2" value="新規登録"></div>
登録実行すると、下記のエラーが出て登録できませんでした。
現時点で動作確認はされましたか？

<img width="854" alt="スクリーンショット 2021-12-15 13 00 42" src="https://user-images.githubusercontent.com/63336345/146120935-4c7a41f2-672a-41de-9493-904ff8d87f8b.png">

2021-12-17 10:59 UTC, miyazaki0505 commented
お疲れ様です！
先ほど再pushさせていただきました。
softdeleteに関しまして、私の環境では、登録ボタン押下後httpsに遷移するためエラーは出てきませんでしたが、dbを確認したところdeleteテーブルはnullになっていましたので、効いていると思っています。
バリデーションはそれぞれうまく動作していますので併せてご確認の程よろしくお願いいたします。

2021-12-19 00:01 UTC, quest-academia approved these changes
修正内容はバッチリできていますね！
素晴らしいです☺️

一応コメントを入れたのでご覧ください☺️

あとはhttps問題ですが
一旦このままマージしてしまってhttps問題は次のブランチで対応してもOKですし
このブランチのままでhttps問題を解消するのでもOKです！

一旦はお疲れ様でした！

2021-12-20 10:26 UTC, closed without merging