Feature/miya/user login
miyazaki0505/miya_portfolio pull request #6
Opened 2021-12-22 01:52 UTC by miyazaki0505

お疲れ様です！
ログイン機能の実装が完了いたしました。

ご確認の程よろしくお願いいたします。

2021-12-23 03:00 UTC, quest-academia requested changes
全体的に綺麗にできていると思います！

ただ、動作確認などでいくつかうまくいっていない部分がありましたので
コメントしました。

その点だけ修正お願いいたします😊

2021-12-23 03:00 UTC, quest-academia commented on resources/views/commons/header.blade.php
> +                <li class="nav-item"><a href="" class="btn btn-outline-secondary mr-1">検索</a></li>
ハンバーガーメニューを押した時に
ボタンが並んでいるのは見た目的に違和感があるので、
<img width="198" alt="スクリーンショット 2021-12-23 11 42 15" src="https://user-images.githubusercontent.com/63336345/147179908-31260625-c44e-4b22-9b8e-e6291323fae2.png">

普通のリンクだけの方がいいと思います！

2021-12-23 03:00 UTC, quest-academia commented on resources/views/auth/login.blade.php
下記バリデーションが英語になっていますね。

<img width="695" alt="スクリーンショット 2021-12-23 11 45 12" src="https://user-images.githubusercontent.com/63336345/147180173-5bb2a17c-618e-4062-ae2e-0fa274a7300f.png">

2021-12-23 03:00 UTC, quest-academia commented on resources/views/commons/header.blade.php
> +                <li class="nav-item"><a href="" class="btn btn-outline-secondary mr-1">検索</a></li>
あと、左揃えではなく、右揃えの方が自然ですね！

2021-12-23 03:00 UTC, quest-academia commented on app/Http/Middleware/RedirectIfAuthenticated.php
> +            return redirect(config('app.url'). '/logout');
このコードの記述のために
ログイン済のユーザがsignupやloginに移動しようとすると強制でログアウトしてしまいます。
これは
　return redirect('/');
で良いと思いますよ。

2021-12-23 03:00 UTC, quest-academia commented on resources/views/auth/logout.blade.php
> +        </div>
ログアウトページは綺麗にできていて、良い感じだと思います！

2021-12-23 12:51 UTC, miyazaki0505 commented
お疲れ様です！
ご指摘いただいた点を修正いたしました。

ご確認の程よろしくお願いいたします。

2021-12-24 06:16 UTC, quest-academia approved these changes
確認しました！

修正点完璧に直せましたね！
良い感じです✨
いつも通りgitでの操作を十分気をつけて
マージしてください！

宜しくお願いいたします‼️

2021-12-24 09:23 UTC, merged