トップページ画面作成
miyazaki0505/miya_portfolio pull request #9
Opened 2021-12-31 06:10 UTC by miyazaki0505

お疲れ様です！
トップページ画面を作成いたしました。

一番最初に表示される画面のため、そのようにルーティングしています。
ご確認よろしくお願いいたします。

2022-01-01 05:28 UTC, SekiYukihiro requested changes
少しコメントしました！

また、TOPページの見た目に関して
具体的にどの部分をどのように配置したかったなどありますか？

それをおっしゃっていただければ
できる限りアドバイスします！

2022-01-01 05:28 UTC, SekiYukihiro commented on app/Http/Controllers/UsersController.php
> +        $projects = DB::table('projects')->orderBy('id', 'desc')->paginate(5);
こちらはDB::というかきかたでも悪くないのですが
他と統一するためにできれば
Project::
を使いましょう！

2022-01-01 11:51 UTC, miyazaki0505 commented
お疲れ様です！

指摘点の修正が完了しました。
ご確認よろしくお願いいたします。

2022-01-02 07:00 UTC, miyazaki0505 commented
お疲れ様です！

勤務地と月額報酬の表示を横並びにすることができました。
詳細ボタンの位置に関しまして、教えていただいた記事を含め試してみましたがどうもうまくいきませんでした。
ただこのままでも見にくいことはないと思うので、このままでいこうと思います。

お時間ある際ご確認よろしくお願いいたします。

2022-01-03 03:05 UTC, miyazaki0505 commented
お疲れ様です！

詳細ボタンの位置を右側上下中央に配置することができました！
ありがとうございます。

ご確認の程宜しくお願いいたします。

2022-01-03 10:14 UTC, merged